language: ruby
cache: bundler
gemfile: Gemfile
before_install:
- gem install bundler
script:
  - bundle exec jekyll algolia push --source _posts -config _config.yml
  #- bundle exec jekyll algolia --source _posts --destination _posts/_site --config _config.yml
  - bundle exec htmlproofer ./_site --disable-external
branches:
  only:
    - master
rvm:
 - 2.4
