language: ruby
cache: bundler
gemfile: Gemfile
before_install:
- gem install bundler
script:
  - bundle exec jekyll algolia
  - bundle exec htmlproofer ./_site --disable-external
branches:
  only:
    - master
rvm:
 - 2.4
