language: ruby
cache: bundler
gemfile: Gemfile
   addons:
    apt:
      update: true
before_install:
- gem install bundler
script:
  - bundle exec jekyll algolia --source _docs 
  # --destination docs/_site --config docs/_config.yml
  - bundle exec htmlproofer ./_site --disable-external
branches:
  only:
    - master
rvm:
 - 2.4
